version: '3.1'
services:
  spboot-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      -  '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=serkan
      - RABBITMQ_DEFAULT_PASS=polat